### ISSUE TITLE
Beautiful webpage ; Customizing your webpage

### ISSUE THREAD

**Issue by dirm02** [sdras/page-transitions-travelapp#11]
I am actually doing a customization of your webpage and I wonder How can I change the map ; in which file , what code ?! PLease and thank you ; Because I dont see your key from googleapi ; I wonder if you did it somehow differently

**Comment by Chris1904** [comment]
you might want to check out mapbox-gl and /pages/index.vue

**Comment by dirm02** [comment]
I will cut down to the chase ; How can I make your map to show Canada ? because i saw the code for it and my head almost blew

**Comment by sdras** [comment]
Hey, you shouldn't try to update my mapbox code, you should generate your own map :) More info here: https://www.mapbox.com/
