### ISSUE TITLE
Devtools in production

### ISSUE THREAD

**Issue by DCzajkowski** [sdras/page-transitions-travelapp#5]
Hello,
thanks for such an awesome demo!

I think it would be beneficial to have Vue Devtools enabled in production, so that it is easier to get a grip of what is happening without a need to download it locally.

I know it is just a simple one-liner `Vue.config.devtools = true`, but I have no clue where to put it in the Nuxt project. In regular Vue template there would be a `main.js` function, whereas where I couldn't find one.

Thanks in advance :)

**Comment by sdras** [comment]
Hi! Thanks for stopping by! 

I don't want to do that, I'd like it to be built as normal and the people who are interested in digging in can clone, run yarn and npm run dev. That's not that many steps and that way they can also play with the code, break things, etc.
